# Generated by Django 4.0.4 on 2022-05-13 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pageFrame', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='name',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='pwd',
            new_name='password',
        ),
    ]
